# Generated by Django 5.2.15 on 2026-07-21 04:58

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, validators=[apps.core.validators.validate_phone_with_country_code])),
                ('linkedin_url', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken, e.g. ["English","Arabic"]')),
                ('current_profession', models.CharField(max_length=200)),
                ('years_experience', models.CharField(max_length=20)),
                ('industries', models.JSONField(default=list, help_text='List of industries with connections, e.g. ["Oil & Gas"]')),
                ('estimated_deals', models.CharField(max_length=20)),
                ('network_description', models.TextField()),
                ('agreed_to_nda', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
