# Generated by Django 5.2.15 on 2026-07-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerapplication',
            name='industries',
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='modules',
            field=models.JSONField(blank=True, default=list, help_text='List of XERXEZ modules they can sell, e.g. ["CRM (Customer Management)","Full ERP Suite (All Modules)"]'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='target_market',
            field=models.CharField(blank=True, default='', help_text='Market/country they intend to sell in, e.g. "Saudi Arabia, Egypt"', max_length=255),
        ),
    ]
