# Generated by Django 5.2.15 on 2026-07-21 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partnerapplication_industries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='portal_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='PartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('package', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('modules_needed', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Deal value once known — commission is computed from this, not stored separately.', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], default='submitted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='partners.partnerapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
