# Generated by Django 5.2.15 on 2026-07-21 09:25

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partnerapplication_portal_token_partnerlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlead',
            name='partner',
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, validators=[apps.core.validators.validate_phone_with_country_code])),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('target_market', models.CharField(blank=True, default='', help_text='Market/country they intend to sell in, e.g. "Saudi Arabia, Egypt"', max_length=255)),
                ('linkedin_url', models.CharField(blank=True, max_length=255)),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken, e.g. ["English","Arabic"]')),
                ('current_profession', models.CharField(max_length=200)),
                ('years_experience', models.CharField(max_length=20)),
                ('modules', models.JSONField(blank=True, default=list, help_text='Packages they applied to sell, e.g. ["Basic","Professional"]')),
                ('estimated_deals', models.CharField(max_length=20)),
                ('network_description', models.TextField()),
                ('agreed_to_nda', models.BooleanField(default=False)),
                ('commission_tier', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('partner_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_deals', models.IntegerField(default=0)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partners', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_company', models.CharField(max_length=200)),
                ('client_contact_person', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=50, validators=[apps.core.validators.validate_phone_with_country_code])),
                ('client_email', models.EmailField(max_length=254)),
                ('client_country', models.CharField(max_length=100)),
                ('package', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('num_employees', models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=10)),
                ('current_system', models.CharField(choices=[('excel', 'Currently using Excel'), ('other_erp', 'Currently using another ERP'), ('nothing', 'No system (manual process)'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('demo_scheduled', 'Demo Scheduled'), ('negotiating', 'Negotiating'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Filled in by XERXEZ once pricing is finalized with the client.', max_digits=14, null=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percent — defaults from the package (10/20/30) at submission, admin may override.', max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated as deal_value * commission_rate / 100 unless set explicitly.', max_digits=14, null=True)),
                ('commission_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('commission_paid_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='partners.partner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='PartnerApplication',
        ),
        migrations.DeleteModel(
            name='PartnerLead',
        ),
    ]
