# Generated by Django 5.2.15 on 2026-07-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_min_stock_level_productcategory_description'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, help_text='Free-text line description; defaults to the product name', max_length=255),
        ),
    ]
