# Generated by Django 5.2.15 on 2026-07-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_commission_notes_alter_commission_order'),
        ('sales', '0002_quotationitem_product_salesorder_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='MLM distributor credited as salesperson for this order, if any — mutually exclusive with salesperson in the UI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_as_salesperson', to='mlm.distributor'),
        ),
    ]
