# Generated by Django 5.2.15 on 2026-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
