# Generated by Django 5.2.15 on 2026-07-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('sales', '0008_quotation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
    ]
