# Migration A (see incident notes): production had 'mlm.0001_initial' already recorded as
# applied under the OLD (pre-rewrite) content, so Django skips re-running 0001 by name and
# never actually created mlm_distributor / mlm_mlmsettings / mlm_payout. This migration creates
# them directly. It is deliberately narrow and touches nothing else: no legacy table (the old
# MLMProfile/CommissionStructure/Transaction/Commission/Earning tables), no mlm_commission
# (handled separately, in its own migration, since it's the one table with an actual name
# collision) — so a problem with any of THOSE can never block this one. Idempotent: every
# statement is CREATE ... IF NOT EXISTS, safe to run against a database that already has the
# correct schema (e.g. local dev).
from django.db import migrations


SQL_CREATE = """
CREATE TABLE IF NOT EXISTS "mlm_distributor" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "distributor_id" varchar(20) NOT NULL UNIQUE,
    "name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "phone" varchar(40) NOT NULL,
    "level" smallint NOT NULL CHECK ("level" >= 0),
    "status" varchar(10) NOT NULL,
    "joining_date" date NOT NULL,
    "total_sales" numeric(14, 2) NOT NULL,
    "total_earnings" numeric(14, 2) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "sponsor_id" bigint NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED,
    "user_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_distributor_distributor_id_6241360a_like" ON "mlm_distributor" ("distributor_id" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "mlm_distributor_sponsor_id_c77afed4" ON "mlm_distributor" ("sponsor_id");
CREATE INDEX IF NOT EXISTS "mlm_distributor_user_id_ca83a019" ON "mlm_distributor" ("user_id");

CREATE TABLE IF NOT EXISTS "mlm_mlmsettings" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "level1_rate" numeric(5, 2) NOT NULL,
    "level2_rate" numeric(5, 2) NOT NULL,
    "level3_rate" numeric(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "mlm_payout" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" numeric(14, 2) NOT NULL,
    "payout_date" date NOT NULL,
    "method" varchar(10) NOT NULL,
    "reference_number" varchar(100) NOT NULL,
    "status" varchar(12) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "distributor_id" bigint NOT NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_payout_distributor_id_f3059dc1" ON "mlm_payout" ("distributor_id");
"""


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        # State already matches (Distributor/MLMSettings/Payout are declared in 0001's
        # CreateModel operations) — this migration only needs to fix the real database.
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(SQL_CREATE, reverse_sql=migrations.RunSQL.noop)],
        ),
    ]
