# Fixes a production migration-history drift: mlm/0001_initial.py was rewritten in place
# (old User-referral design -> new Distributor/Commission/Payout/MLMSettings design), but any
# database that had already recorded 'mlm.0001_initial' as applied under the OLD content skips
# re-running it (Django tracks migrations by name, not content) — leaving old tables in place
# (or, for the brand-new Distributor/Payout/MLMSettings tables, never creating them at all) while
# the application code already expects the new schema. This is a database-only fix: Django's
# migration STATE already matches the new models (from 0001_initial), so only the real tables
# need to catch up — hence SeparateDatabaseAndState with no state_operations.
#
# Idempotent and safe to run on any environment:
#   - A DB that already has the new schema (e.g. local dev, already fixed manually): every
#     statement is a documented no-op (DROP ... IF EXISTS, CREATE ... IF NOT EXISTS, the
#     mlm_commission rebuild only fires if the OLD 'earner_id' column is still present).
#   - A DB still on the old schema (production): drops the old, now-unreferenced tables and
#     creates the new ones so they match exactly what `sqlmigrate mlm 0001` describes.
from django.db import migrations

SQL_FIX = """
DO $$
DECLARE
    row_count bigint;
    tbl text;
BEGIN
    -- Safety guard: never drop a legacy table that actually has rows in it. If any of
    -- these hold real data, abort the whole migration loudly (deploy fails, nothing is
    -- touched) instead of silently discarding it — this environment's data was never
    -- confirmed empty the way local dev was.
    FOREACH tbl IN ARRAY ARRAY['mlm_commissionstructure', 'mlm_earning', 'mlm_mlmprofile', 'mlm_transaction'] LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = tbl) THEN
            EXECUTE format('SELECT COUNT(*) FROM %I', tbl) INTO row_count;
            IF row_count > 0 THEN
                RAISE EXCEPTION 'Legacy MLM table % has % row(s) — aborting migration 0002 without dropping anything. Investigate and clear/migrate this data manually before retrying.', tbl, row_count;
            END IF;
        END IF;
    END LOOP;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'mlm_commission' AND column_name = 'earner_id'
    ) THEN
        EXECUTE 'SELECT COUNT(*) FROM mlm_commission' INTO row_count;
        IF row_count > 0 THEN
            RAISE EXCEPTION 'Legacy mlm_commission has % row(s) — aborting migration 0002 without dropping anything. Investigate and clear/migrate this data manually before retrying.', row_count;
        END IF;
    END IF;

    DROP TABLE IF EXISTS mlm_commissionstructure CASCADE;
    DROP TABLE IF EXISTS mlm_earning CASCADE;
    DROP TABLE IF EXISTS mlm_mlmprofile CASCADE;
    DROP TABLE IF EXISTS mlm_transaction CASCADE;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'mlm_commission' AND column_name = 'earner_id'
    ) THEN
        DROP TABLE mlm_commission CASCADE;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "mlm_distributor" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "distributor_id" varchar(20) NOT NULL UNIQUE,
    "name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "phone" varchar(40) NOT NULL,
    "level" smallint NOT NULL CHECK ("level" >= 0),
    "status" varchar(10) NOT NULL,
    "joining_date" date NOT NULL,
    "total_sales" numeric(14, 2) NOT NULL,
    "total_earnings" numeric(14, 2) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "sponsor_id" bigint NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED,
    "user_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_distributor_distributor_id_6241360a_like" ON "mlm_distributor" ("distributor_id" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "mlm_distributor_sponsor_id_c77afed4" ON "mlm_distributor" ("sponsor_id");
CREATE INDEX IF NOT EXISTS "mlm_distributor_user_id_ca83a019" ON "mlm_distributor" ("user_id");

CREATE TABLE IF NOT EXISTS "mlm_mlmsettings" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "level1_rate" numeric(5, 2) NOT NULL,
    "level2_rate" numeric(5, 2) NOT NULL,
    "level3_rate" numeric(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "mlm_payout" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "amount" numeric(14, 2) NOT NULL,
    "payout_date" date NOT NULL,
    "method" varchar(10) NOT NULL,
    "reference_number" varchar(100) NOT NULL,
    "status" varchar(12) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "distributor_id" bigint NOT NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_payout_distributor_id_f3059dc1" ON "mlm_payout" ("distributor_id");

CREATE TABLE IF NOT EXISTS "mlm_commission" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "level" smallint NOT NULL CHECK ("level" >= 0),
    "rate" numeric(5, 2) NOT NULL,
    "amount" numeric(14, 2) NOT NULL,
    "status" varchar(10) NOT NULL,
    "created_date" timestamp with time zone NOT NULL,
    "distributor_id" bigint NOT NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED,
    "order_id" bigint NOT NULL REFERENCES "sales_salesorder" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_commission_distributor_id_cf656534" ON "mlm_commission" ("distributor_id");
CREATE INDEX IF NOT EXISTS "mlm_commission_order_id_6e360347" ON "mlm_commission" ("order_id");
"""


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(SQL_FIX, reverse_sql=migrations.RunSQL.noop)],
        ),
    ]
