# Migration B (see incident notes / Migration A in 0002_create_new_mlm_tables.py).
#
# Isolated from Migration A on purpose: this is the one table with an actual name collision
# (mlm_commission, reused from the old MLMProfile/CommissionStructure/Transaction/Commission/
# Earning design), so it's the one place a real conflict could still block something. Keeping
# it in its own migration means a problem here can never undo Migration A's already-committed,
# risk-free table creation.
#
# mlm_commissionstructure (and the other legacy tables — mlm_earning, mlm_mlmprofile,
# mlm_transaction) are deliberately left alone entirely: nothing in this migration reads,
# writes, or drops them, except a one-time copy of the 3 known commission-rate rows into the
# new MLMSettings singleton (confirmed via Railway console: just rate config, no transactional
# data — level 1/2/3 at 10.10% / 5.00% / 2.00%). The source table itself is never touched.
#
# The `order` FK depends on 'sales' — safe to declare here since 0003 is a migration name that
# was never previously applied anywhere (unlike 0001, which already had a production-recorded
# timestamp from before any 'sales' migration existed — see feedback_migration_rewrites_are_dangerous).
import django.db.models.deletion
from django.db import migrations, models


SQL_FIX_COMMISSION = """
DO $$
DECLARE
    row_count bigint;
BEGIN
    -- Only touches mlm_commission. mlm_commissionstructure/earning/mlmprofile/transaction are
    -- never referenced here.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'mlm_commission' AND column_name = 'earner_id'
    ) THEN
        EXECUTE 'SELECT COUNT(*) FROM mlm_commission' INTO row_count;
        IF row_count > 0 THEN
            RAISE EXCEPTION 'Legacy mlm_commission has % row(s) — aborting this migration without dropping anything. Investigate and clear/migrate this data manually before retrying.', row_count;
        END IF;
        DROP TABLE mlm_commission CASCADE;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "mlm_commission" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "level" smallint NOT NULL CHECK ("level" >= 0),
    "rate" numeric(5, 2) NOT NULL,
    "amount" numeric(14, 2) NOT NULL,
    "status" varchar(10) NOT NULL,
    "created_date" timestamp with time zone NOT NULL,
    "distributor_id" bigint NOT NULL REFERENCES "mlm_distributor" ("id") DEFERRABLE INITIALLY DEFERRED,
    "order_id" bigint NOT NULL REFERENCES "sales_salesorder" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX IF NOT EXISTS "mlm_commission_distributor_id_cf656534" ON "mlm_commission" ("distributor_id");
CREATE INDEX IF NOT EXISTS "mlm_commission_order_id_6e360347" ON "mlm_commission" ("order_id");
"""


def copy_legacy_rates_into_settings(apps, schema_editor):
    """One-time copy of the 3 known commission-rate rows (confirmed rate-config-only, no
    transactional data) into the new MLMSettings singleton. Read-only against
    mlm_commissionstructure — never writes to or drops it."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM information_schema.tables WHERE table_name = 'mlm_commissionstructure'
        """)
        if not cursor.fetchone():
            return  # table doesn't exist in this environment (e.g. fresh/CI) — nothing to copy
        cursor.execute("SELECT level, commission_rate FROM mlm_commissionstructure WHERE level IN (1, 2, 3)")
        rates = dict(cursor.fetchall())

    if not rates:
        return

    MLMSettings = apps.get_model('mlm', 'MLMSettings')
    settings_obj, _ = MLMSettings.objects.get_or_create(pk=1)
    if 1 in rates:
        settings_obj.level1_rate = rates[1]
    if 2 in rates:
        settings_obj.level2_rate = rates[2]
    if 3 in rates:
        settings_obj.level3_rate = rates[3]
    settings_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_create_new_mlm_tables'),
        ('sales', '0002_quotationitem_product_salesorder_salesperson_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Commission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('level', models.PositiveSmallIntegerField(help_text="1, 2 or 3 — how many levels above the order's originating distributor this earner sits")),
                        ('rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 10.00', max_digits=5)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                        ('created_date', models.DateTimeField(auto_now_add=True)),
                        ('distributor', models.ForeignKey(help_text='The earner', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mlm.distributor')),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='sales.salesorder')),
                    ],
                    options={
                        'ordering': ['-created_date'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(SQL_FIX_COMMISSION, reverse_sql=migrations.RunSQL.noop),
            ],
        ),
        migrations.RunPython(copy_legacy_rates_into_settings, migrations.RunPython.noop),
    ]
