# Generated by Django 5.2.15 on 2026-07-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_create_commission_table'),
        ('sales', '0002_quotationitem_product_salesorder_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='commission',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Null for manually-added commissions not tied to a sales order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_commissions', to='sales.salesorder'),
        ),
    ]
