# Generated by Django 5.2.15 on 2026-07-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0005_delete_zero_amount_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='commission',
            field=models.OneToOneField(blank=True, help_text='The commission this payout was auto-created from, on approval. Null for manually-created payouts (e.g. one payout bundling several commissions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='mlm.commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
