# Generated by Django 5.2.15 on 2026-07-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('mlm', '0007_commission_created_by_distributor_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='mlmsettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='payout',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
    ]
