# Generated by Django 5.2.15 on 2026-07-16 05:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
    ]
