# Generated by Django 5.2.15 on 2026-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_seed_xerxez'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=10, help_text='Maximum number of users allowed for this company'),
        ),
    ]
