# Generated by Django 5.2.15 on 2026-07-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_product_image_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Inventory warehouse the stock was received into — defaults to the first active warehouse if left blank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='inventory.warehouse'),
        ),
    ]
