# Generated by Django 5.2.15 on 2026-07-17 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_goodsreceipt_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-character GST Identification Number, e.g. 29ABCDE1234F1Z5 — required for GST input tax credit on Indian purchase records/bills.', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN, e.g. 29ABCDE1234F1Z5.', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
    ]
