# Generated by Django 5.2.15 on 2026-07-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(help_text='e.g. AST-001', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('machinery', 'Machinery'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('tool', 'Tool'), ('it_equipment', 'IT Equipment'), ('safety', 'Safety'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('lost', 'Lost')], default='active', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual % depreciation', max_digits=5)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('maintenance_interval_days', models.IntegerField(default=90)),
                ('qr_code', models.CharField(blank=True, help_text='QR code payload (data/URL) encoded into qr_code_image', max_length=255)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='assets/qr/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency'), ('inspection', 'Inspection')], max_length=20)),
                ('performed_by', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='asset_management.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('opening_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('closing_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='asset_management.asset')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('asset', 'year')},
            },
        ),
    ]
