# Generated by Django 5.2.15 on 2026-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='budget_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='budget_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='hear_about_us',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='plan_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='team_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
