# Generated by Django 5.2.15 on 2026-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_budget_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='approx_budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='cloud_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='current_infra',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deployment_env',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='migration_needed',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='num_developers',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='project_timeline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='topics_of_interest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='training_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='training_team_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
