# Generated by Django 5.2.15 on 2026-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_approx_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='training_duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='topics_of_interest',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='training_mode',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
