# Generated by Django 5.2.15 on 2026-07-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='timeline',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
