# Generated by Django 5.2.15 on 2026-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactmessage_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='erp_modules',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
