# Generated by Django 5.2.15 on 2026-07-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_contactmessage_assigned_to_contactmessage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='current_challenge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
