# Generated by Django 6.0.6 on 2026-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_contactmessage_current_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='course_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
