# Generated by Django 6.0.6 on 2026-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_contactmessage_coupon_code_contactmessage_course_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='course_names',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='platform_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
