# Generated by Django 6.0.6 on 2026-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contactmessage_course_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='course_format',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
