# Generated by Django 5.2.15 on 2026-07-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0002_document_expiry_date_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='documentaudittrail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company'),
        ),
    ]
