# Generated by Django 5.2.15 on 2026-07-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_product_image_and_more'),
        ('logistics', '0002_shipment_delivery_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='origin_warehouse',
            field=models.ForeignKey(blank=True, help_text='Inventory warehouse this shipment originates from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, help_text='Free-text origin label — auto-filled from origin_warehouse when one is selected', max_length=255),
        ),
    ]
