# Generated by Django 5.2.15 on 2026-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_cleanup_categories_and_data_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
