# Generated by Django 5.2.15 on 2026-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customernote_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, help_text='For task-type activities — when it is due', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('outbound', 'Outbound'), ('event', 'Event'), ('social', 'Social Media'), ('email', 'Email'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["VIP","Prospect"]'),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.PositiveSmallIntegerField(default=0, help_text='Win probability, 0-100'),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('task', 'Task'), ('note', 'Note')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('outbound', 'Outbound'), ('event', 'Event'), ('social', 'Social Media'), ('email', 'Email'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
