# Generated by Django 5.2.15 on 2026-07-16 05:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_activity_completed_activity_due_date_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
    ]
