# Generated by Django 5.2.15 on 2026-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_contact_phone_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('task', 'Task'), ('follow_up', 'Follow Up'), ('note', 'Note')], default='note', max_length=20),
        ),
    ]
