# Generated by Django 5.2.15 on 2026-07-10 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendance_status_shift_salarystructure_payroll_payslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('id_proof', 'ID Proof'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='hr/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_employee_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('contract_end', 'Contract End')], max_length=20)),
                ('last_working_day', models.DateField()),
                ('notice_period_days', models.IntegerField(default=30)),
                ('exit_interview_done', models.BooleanField(default=False)),
                ('final_settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_exit_management',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_onboarding_checklist',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('goals_achieved', models.TextField(blank=True)),
                ('areas_improvement', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hr.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_performance_review',
                'ordering': ['-review_date'],
            },
        ),
    ]
