# Generated by Django 5.2.15 on 2026-07-16 05:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employeedocument_exitmanagement_onboardingchecklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
    ]
