# Generated by Django 5.2.15 on 2026-07-22 09:23

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_attendance_company_department_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=40, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/employees/photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('AED', 'AED'), ('USD', 'USD')], default='INR', max_length=3),
        ),
    ]
