# Generated by Django 5.2.15 on 2026-07-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#c8a84b', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='briefcase', max_length=50),
        ),
    ]
