# Generated by Django 5.2.15 on 2026-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_department_color_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='annual', max_length=20),
        ),
    ]
