# Generated by Django 5.2.15 on 2026-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_leaverequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True when an admin added/edited this record by hand rather than the employee clocking in/out.'),
        ),
    ]
