# Generated by Django 5.2.15 on 2026-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_holiday_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='rate',
            field=models.CharField(choices=[('1.5x', '1.5x'), ('2x', '2x'), ('2.5x', '2.5x')], default='1.5x', max_length=10),
        ),
    ]
