# Generated by Django 5.2.15 on 2026-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_overtime_rejection_reason_alter_overtime_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime payment amount, entered manually by the admin (not auto-calculated).', max_digits=10),
        ),
    ]
