# Generated by Django 5.2.15 on 2026-07-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_max_users'),
        ('hr', '0013_overtime_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=20)),
                ('days_allowed', models.IntegerField(default=0)),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='companies.company')),
            ],
            options={
                'db_table': 'hr_leavepolicy',
                'ordering': ['leave_type'],
                'unique_together': {('company', 'leave_type')},
            },
        ),
    ]
