# Generated by Django 5.2.15 on 2026-07-23 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_duration',
            field=models.IntegerField(default=30, help_text='Break duration in minutes'),
        ),
        migrations.AddField(
            model_name='shift',
            name='color',
            field=models.CharField(default='#c8a84b', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 23, 7, 48, 1, 167148, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_period',
            field=models.IntegerField(default=10, help_text='Minutes late allowed before marked late'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night'), ('Rotational', 'Rotational')], default='Morning', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['Monday', 'Tuesday', ...]"),
        ),
    ]
