# Generated by Django 5.2.15 on 2026-07-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_shift_break_duration_shift_color_shift_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name']},
        ),
    ]
