# Generated by Django 5.2.15 on 2026-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_shift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Automatically applies every year on this same month/day.'),
        ),
    ]
