# Generated by Django 5.2.15 on 2026-07-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_holiday_is_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='document_number',
            field=models.CharField(blank=True, help_text='Passport number, visa number, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_hr_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('emirates_id', 'Emirates ID'), ('aadhar_card', 'Aadhar Card'), ('visa', 'Visa'), ('employment_contract', 'Employment Contract'), ('offer_letter', 'Offer Letter'), ('experience_certificate', 'Experience Certificate'), ('educational_certificate', 'Educational Certificate'), ('medical_certificate', 'Medical Certificate'), ('insurance', 'Insurance Document'), ('nda', 'NDA'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_documents/'),
        ),
    ]
