# Generated by Django 5.2.15 on 2026-07-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_employeedocument_document_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hr_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('aadhar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('emirates_id', 'Emirates ID'), ('visa', 'Visa'), ('employment_contract', 'Employment Contract'), ('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('experience_certificate', 'Experience Letter'), ('relieving_letter', 'Relieving Letter'), ('educational_certificate', 'Educational Certificate'), ('degree_certificate', 'Degree Certificate'), ('marksheet', 'Marksheet'), ('medical_certificate', 'Medical Certificate'), ('insurance', 'Insurance Document'), ('bank_account_details', 'Bank Account Details'), ('cancelled_cheque', 'Cancelled Cheque'), ('salary_slip', 'Salary Slip'), ('background_verification', 'Background Verification'), ('nda', 'NDA'), ('other', 'Other')], max_length=30),
        ),
    ]
