# Generated by Django 5.2.15 on 2026-07-23 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_employeedocument_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingchecklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboarding_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='category',
            field=models.CharField(choices=[('pre_joining', 'Pre-Joining'), ('day_1', 'Day 1'), ('first_week', 'First Week'), ('first_month', 'First Month')], default='pre_joining', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
