# Generated by Django 5.2.15 on 2026-07-23 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_max_users'),
        ('hr', '0020_onboardingchecklist_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exitmanagement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='deductions_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='exit_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='exit_interview_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='gratuity_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='leave_encashment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='notice_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='notice_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='pending_leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='pending_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='pending_salary_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='settlement_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='settlement_payment_mode',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=20),
        ),
        migrations.AddField(
            model_name='exitmanagement',
            name='settlement_reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('serving_notice', 'Serving Notice'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='exitmanagement',
            name='reason',
            field=models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('absconding', 'Absconding'), ('contract_end', 'End of Contract')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExitChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('before_last_day', 'Before Last Day'), ('it_access', 'IT & Access'), ('hr_finance', 'HR & Finance')], default='before_last_day', max_length=20)),
                ('task', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exit_tasks', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='companies.company')),
                ('exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='hr.exitmanagement')),
            ],
            options={
                'db_table': 'hr_exit_checklist',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=200)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('job_satisfaction_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('management_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_environment_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('liked_most', models.TextField(blank=True)),
                ('could_improve', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='hr.exitmanagement')),
            ],
            options={
                'db_table': 'hr_exit_interview',
            },
        ),
    ]
