# Generated by Django 5.2.15 on 2026-07-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_product_image_and_more'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, help_text='Free-text line description; defaults to the product name', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online Gateway'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
