# Generated by Django 5.2.15 on 2026-07-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_activity_completed_activity_due_date_customer_city_and_more'),
        ('invoicing', '0002_invoiceitem_product_alter_invoiceitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online Gateway'), ('credit_note', 'Credit Note'), ('other', 'Other')], default='bank', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. CN-001', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='issued', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='crm.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Line description on generated invoices, e.g. "Monthly retainer"', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Pre-tax line amount; 18% GST is added on the generated invoice, same as a manual invoice', max_digits=14)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='crm.customer')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
    ]
