# Generated by Django 5.2.15 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0002_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmaprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
