# Generated by Django 5.2.15 on 2026-07-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0007_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
