# Generated by Django 6.0.6 on 2026-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0010_course_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='confirm_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='course_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='estimated_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='previous_teaching_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='proposed_course_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lmaprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lmaprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lmaprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
