# Generated by Django 6.0.6 on 2026-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0011_instructorapplication_agree_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='applicant_type',
            field=models.CharField(choices=[('individual', 'Individual Instructor'), ('company', 'Company / Organisation')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='company_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
