# Generated by Django 6.0.6 on 2026-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0013_lesson_content_type_lesson_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonassignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonassignment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
