# Generated by Django 6.0.6 on 2026-09-21 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0014_alter_lessonassignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/issued/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to='certificates/templates/'),
        ),
    ]
