# Generated by Django 6.0.6 on 2026-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma', '0015_certificate_certificate_file_certificate_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
