"""
Pre-migrate fix for Railway deployment.
Resolves InconsistentMigrationHistory when accounts.0001_initial is missing
but admin.0001_initial (which depends on it) is already applied.
Also ensures contact_contactmessage table exists as a safety net.
Run via: python manage.py shell -c "exec(open('scripts/fix_migrations.py').read())"
"""
from django.db import connection
from django.utils import timezone

try:
    with connection.cursor() as c:
        # ── ensure django_migrations table exists before querying it ──
        c.execute("""
            SELECT COUNT(*) FROM information_schema.tables
            WHERE table_schema='public' AND table_name='django_migrations'
        """)
        migrations_table_exists = c.fetchone()[0]

        if not migrations_table_exists:
            print("fix_migrations: django_migrations table not found — skipping pre-checks, letting migrate handle it")
        else:
            # ── accounts fix ──────────────────────────────────────────────────
            c.execute("SELECT COUNT(*) FROM django_migrations WHERE app='accounts' AND name='0001_initial'")
            migration_recorded = c.fetchone()[0]

            c.execute("""
                SELECT COUNT(*) FROM information_schema.tables
                WHERE table_schema='public' AND table_name='accounts_user'
            """)
            table_exists = c.fetchone()[0]

            if migration_recorded and table_exists:
                print("fix_migrations: accounts OK — nothing to do")
            else:
                print(f"fix_migrations: migration_recorded={bool(migration_recorded)}, table_exists={bool(table_exists)}")

                if not table_exists:
                    print("fix_migrations: creating accounts_user tables...")
                    c.execute('''
                        CREATE TABLE IF NOT EXISTS "accounts_user" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "password" varchar(128) NOT NULL,
                            "last_login" timestamp with time zone NULL,
                            "is_superuser" boolean NOT NULL,
                            "username" varchar(150) NOT NULL UNIQUE,
                            "first_name" varchar(150) NOT NULL,
                            "last_name" varchar(150) NOT NULL,
                            "email" varchar(254) NOT NULL,
                            "is_staff" boolean NOT NULL,
                            "is_active" boolean NOT NULL,
                            "date_joined" timestamp with time zone NOT NULL,
                            "role" varchar(20) NOT NULL DEFAULT 'admin',
                            "last_login_at" timestamp with time zone NULL
                        )
                    ''')
                    c.execute('''
                        CREATE TABLE IF NOT EXISTS "accounts_user_groups" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "user_id" bigint NOT NULL,
                            "group_id" integer NOT NULL
                        )
                    ''')
                    c.execute('''
                        CREATE TABLE IF NOT EXISTS "accounts_user_user_permissions" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "user_id" bigint NOT NULL,
                            "permission_id" integer NOT NULL
                        )
                    ''')
                    for sql in [
                        'CREATE INDEX IF NOT EXISTS "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops)',
                        'ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_uniq" UNIQUE ("user_id", "group_id")',
                        'ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_fk" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED',
                        'ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_fk" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED',
                        'CREATE INDEX IF NOT EXISTS "accounts_user_groups_user_idx" ON "accounts_user_groups" ("user_id")',
                        'CREATE INDEX IF NOT EXISTS "accounts_user_groups_group_idx" ON "accounts_user_groups" ("group_id")',
                        'ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_perms_uniq" UNIQUE ("user_id", "permission_id")',
                        'ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_perms_user_fk" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED',
                        'ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_perms_perm_fk" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED',
                        'CREATE INDEX IF NOT EXISTS "accounts_user_perms_user_idx" ON "accounts_user_user_permissions" ("user_id")',
                        'CREATE INDEX IF NOT EXISTS "accounts_user_perms_perm_idx" ON "accounts_user_user_permissions" ("permission_id")',
                    ]:
                        try:
                            c.execute(sql)
                        except Exception as e:
                            print(f"  skip (already exists): {e}")
                    print("fix_migrations: accounts_user table created")

                if not migration_recorded:
                    c.execute(
                        "INSERT INTO django_migrations (app, name, applied) VALUES (%s, %s, %s)",
                        ['accounts', '0001_initial', timezone.now()]
                    )
                    print("fix_migrations: accounts.0001_initial marked as applied")

            # ── contact_contactmessage safety net ─────────────────────────────
            c.execute("""
                SELECT COUNT(*) FROM information_schema.tables
                WHERE table_schema='public' AND table_name='contact_contactmessage'
            """)
            contact_table_exists = c.fetchone()[0]

            if contact_table_exists:
                print("fix_migrations: contact_contactmessage OK")
            else:
                print("fix_migrations: contact_contactmessage missing — creating directly...")
                c.execute('''
                    CREATE TABLE IF NOT EXISTS "contact_contactmessage" (
                        "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "full_name"  varchar(200) NOT NULL,
                        "email"      varchar(254) NOT NULL,
                        "phone"      varchar(50)  NOT NULL DEFAULT '',
                        "company"    varchar(200) NOT NULL DEFAULT '',
                        "service"    varchar(200) NOT NULL DEFAULT '',
                        "urgency"    varchar(20)  NOT NULL DEFAULT 'normal',
                        "subject"    varchar(300) NOT NULL DEFAULT '',
                        "message"    text         NOT NULL,
                        "created_at" timestamp with time zone NOT NULL DEFAULT now(),
                        "is_read"    boolean      NOT NULL DEFAULT false
                    )
                ''')
                print("fix_migrations: contact_contactmessage created")

                # Record the migration so Django doesn't try to re-apply it
                c.execute("SELECT COUNT(*) FROM django_migrations WHERE app='contact' AND name='0001_initial'")
                if not c.fetchone()[0]:
                    c.execute(
                        "INSERT INTO django_migrations (app, name, applied) VALUES (%s, %s, %s)",
                        ['contact', '0001_initial', timezone.now()]
                    )
                    print("fix_migrations: contact.0001_initial marked as applied")

    print("fix_migrations: done")

except Exception as exc:
    print(f"fix_migrations: WARNING — script failed ({exc}), continuing with migrate anyway")
