# Generated by Django 5.2.15 on 2026-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_seed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('module_admin', 'Module Admin'), ('regular_user', 'Regular User'), ('read_only', 'Read Only')], default='regular_user', max_length=20),
        ),
    ]
