# Generated by Django 5.2.15 on 2026-07-16 05:54

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.core.validators.validate_phone_with_country_code]),
        ),
    ]
