# Generated by Django 6.0.6 on 2026-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_logo', models.ImageField(blank=True, null=True, upload_to='partner_courses/logos/')),
                ('partner_website', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='partner_courses/thumbnails/')),
                ('affiliate_link', models.URLField()),
                ('affiliate_code', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-is_featured', '-created_at'],
            },
        ),
    ]
